server:
  port: 9001
spring:
  application:
    name: producer1
#  profiles:
#    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
